### ISSUE TITLE
could not find recipe server for cookbook mysql

### ISSUE THREAD

**Issue by samblabla** [scourgen/Vagrant-PHP-Stack#3]
mysql出现问题，could not find recipe server for cookbook mysql。根据网上资料，说是mysql升级了 The new version (6.0) doesn't provide recipes, just LWRP (mysql_service resource).
应该怎么解决？

**Comment by scourgen** [comment]
这里有个解决方案：http://stackoverflow.com/questions/28755285/whats-wrong-with-my-chef-configuration

**Comment by samblabla** [comment]
感谢,已经改用mysql 5.6了,期待大师的vagrant的教程.
