### ISSUE TITLE
an error occured while loading web debug toolbar 

### ISSUE THREAD

**Issue by YangHongchen** [scourgen/Vagrant-PHP-Stack#4]
Aftrer I created an symfony project(Version 2.8.5) , I visit the front controller file app_dev.php ,an error occurred like the title says. I don't know why, I searched the the solution,but no answer, please help ...THKS

**Comment by scourgen** [comment]
It will be more useful if you can check the error log of Symfony.

**Comment by YangHongchen** [comment]
nginx provides a config demo :https://www.nginx.com/resources/wiki/start/topics/recipes/symfony/
